### ISSUE TITLE
IteratorPrototype should have no `toStringTag` property

### ISSUE THREAD

**Issue by amangeot** [medikoo/es6-iterator#6]
Hello,
I have a conflict between regenerator and the way Iterator is polyfilled that I mentioned on regenerator's repo: https://github.com/facebook/regenerator/issues/320.

The problem is regenerator uses `IteratorPrototype` for its `GeneratorFunction`, and it crashes when it tries to write on `GeneratorFunction.prototype.toStringTag` which is not writable.

The spec mentions no `toStringTag` property for `IteratorPrototype`:
https://tc39.github.io/ecma262/#sec-%iteratorprototype%-object

Is it possible to remove `toStringTag` from `IteratorPrototype`?

**Comment by medikoo** [comment]
Great thanks for report. Fixed with 2d17786, published with v2.0.2
